-- Load Lyme Disease Data --

SELECT * FROM LD_CASES
FETCH FIRST 10 ROWS ONLY;

SELECT COUNT(*) FROM LD_CASES;


-- Load Tick Data --

SELECT * FROM TICK_DF
FETCH FIRST 10 ROWS ONLY;

SELECT COUNT(*) FROM TICK_DF;


-- Creating the Counties table -- 

CREATE TABLE COUNTIES (
    FIPS VARCHAR(5) PRIMARY KEY,
    COUNTY_NAME VARCHAR(100),
    STATE_NAME VARCHAR(50)
);

INSERT INTO COUNTIES (FIPS, COUNTY_NAME, STATE_NAME)
SELECT DISTINCT FIPS, CTYNAME, STNAME
FROM LD_CASES;

SELECT COUNT(*) FROM COUNTIES;
    
DROP TABLE COUNTIES;

-- Creating a LD Case table --
CREATE TABLE CASE_DATA (
    FIPS VARCHAR2(5),
    INCIDENCE_STATUS VARCHAR2(20),
    Y2001 NUMBER, Y2002 NUMBER, Y2003 NUMBER, Y2004 NUMBER, Y2005 NUMBER,
    Y2006 NUMBER, Y2007 NUMBER, Y2008 NUMBER, Y2009 NUMBER, Y2010 NUMBER,
    Y2011 NUMBER, Y2012 NUMBER, Y2013 NUMBER, Y2014 NUMBER, Y2015 NUMBER,
    Y2016 NUMBER, Y2017 NUMBER, Y2018 NUMBER, Y2019 NUMBER, Y2020 NUMBER,
    Y2021 NUMBER, Y2022 NUMBER, Y2023 NUMBER,
    CONSTRAINT fk_case_county FOREIGN KEY (FIPS) REFERENCES COUNTIES(FIPS)
);

INSERT INTO CASE_DATA (FIPS, INCIDENCE_STATUS, Y2001, Y2002, Y2003, Y2004, Y2005, Y2006, Y2007, Y2008, Y2009, Y2010, Y2011, 
Y2012, Y2013, Y2014, Y2015, Y2016, Y2017, Y2018, Y2019, Y2020, Y2021, Y2022, Y2023)
SELECT FIPS, STSTATUS, Cases2001, Cases2002, Cases2003, Cases2004, Cases2005, Cases2006, Cases2007, Cases2008, Cases2009, Cases2010, 
Cases2011, Cases2012, Cases2013, Cases2014, Cases2015, Cases2016, Cases2017, Cases2018, Cases2019, Cases2020, cases2021, cases2022, cases2023
FROM LD_CASES;

SELECT COUNT(*) FROM CASE_DATA; 

DROP TABLE CASE_DATA;

-- Creating a table for Tick data --
CREATE TABLE TICK_STATUS (
    FIPS VARCHAR2(5),
    SCAPULARIS_STATUS VARCHAR2(20),
    PACIFICUS_STATUS VARCHAR2(20),
    CONSTRAINT fk_tick_county FOREIGN KEY (FIPS) REFERENCES COUNTIES(FIPS)
);

UPDATE TICK_DF
SET FIPS = '46102'
WHERE FIPS = '46113';

INSERT INTO TICK_STATUS (FIPS, SCAPULARIS_STATUS, PACIFICUS_STATUS)
SELECT FIPS, IXODES_SCAPULARIS_COUNTY_STATUS, IXODES_PACIFICUS_COUNTY_STATUS
FROM TICK_DF
WHERE FIPS IN (SELECT FIPS FROM COUNTIES);

DROP TABLE TICK_STATUS;

SELECT COUNT(*) FROM TICK_STATUS;

-- One row of data did not import into the table TICK_STATUS -- 
-- SELECT * FROM TICK_DF
-- WHERE FIPS NOT IN (SELECT FIPS FROM COUNTIES);

-- SELECT * FROM COUNTIES WHERE FIPS = '46102' OR FIPS = '46113';


SELECT c.FIPS, c.COUNTY_NAME, c.STATE_NAME, t.SCAPULARIS_STATUS, cd.Y2020, cd.Y2021, cd.Y2022, cd.Y2023
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
FETCH FIRST 20 ROWS ONLY;


SELECT SCAPULARIS_STATUS,
       AVG(Y2020) AS avg_2020,
       AVG(Y2021) AS avg_2021,
       AVG(Y2022) AS avg_2022,
       AVG(Y2023) AS avg_2023
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
GROUP BY SCAPULARIS_STATUS;

-- Across all 4 years from 2020-2023, Estbalished status had the highest average cases of ticks between those given years --

SELECT cd.INCIDENCE_STATUS, t.SCAPULARIS_STATUS,
       AVG(cd.Y2021) AS avg_2021,
       AVG(cd.Y2022) AS avg_2022
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
GROUP BY cd.INCIDENCE_STATUS, t.SCAPULARIS_STATUS;

-- Average cases jumped from 40 cases in 2021 to 116 in 2022 in high incident counties. -- 


-- Population Dataset by County -- 
SELECT * FROM POPULATION_DF
FETCH FIRST 10 ROWS ONLY;

SELECT COUNT(*) FROM POPULATION_DF;

CREATE TABLE POPULATION (
    FIPS VARCHAR2(5),
    POP_2020 NUMBER,
    POP_2021 NUMBER,
    POP_2022 NUMBER,
    POP_2023 NUMBER,
    CONSTRAINT fk_pop_county FOREIGN KEY (FIPS) REFERENCES COUNTIES(FIPS)
);

INSERT INTO POPULATION (FIPS, POP_2020, POP_2021, POP_2022, POP_2023)
SELECT FIPS, POPESTIMATE2020, POPESTIMATE2021, POPESTIMATE2022, POPESTIMATE2023
FROM POPULATION_DF
WHERE FIPS IN (SELECT FIPS FROM COUNTIES);

DROP TABLE POPULATION; 

-- Checking the missing row -- 
SELECT * FROM POPULATION_DF
WHERE FIPS NOT IN (SELECT FIPS FROM COUNTIES);

-- Calculating case rate per 100,000 people to ensure fair anaylsis across counties -- 

SELECT c.FIPS, c.COUNTY_NAME, c.STATE_NAME, t.SCAPULARIS_STATUS,
       (cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) AS total_cases,
       p.POP_2023,
       ROUND(((cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) / p.POP_2023) * 100000, 2) AS case_rate_per_100k
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
JOIN POPULATION p ON c.FIPS = p.FIPS
FETCH FIRST 20 ROWS ONLY;


SELECT c.FIPS, c.COUNTY_NAME, c.STATE_NAME, t.SCAPULARIS_STATUS,
       (cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) AS total_cases,
       p.POP_2023,
       ROUND(((cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) / p.POP_2023) * 100000, 2) AS case_rate_per_100k
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
JOIN POPULATION p ON c.FIPS = p.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
ORDER BY case_rate_per_100k ASC
FETCH FIRST 20 ROWS ONLY;

-- Established tick population, but 0 case counties -- 
SELECT cd.INCIDENCE_STATUS, COUNT(*) AS zero_case_established_counties
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
AND (cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) = 0
GROUP BY cd.INCIDENCE_STATUS;

-- Overall established counties -- 
SELECT cd.INCIDENCE_STATUS, COUNT(*) AS total_established_counties
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
GROUP BY cd.INCIDENCE_STATUS;

-- Low Incidence States: About 34.1% of established counties report 0 cases of lyme disease --
-- High Incidence States: About 0.61 % of established counties report 0 cases of lyme disease -- 

-- Rural/Urban Dataset -- 
SELECT * FROM URBAN_RURAL_DF
FETCH FIRST 10 ROWS ONLY;

SELECT COUNT(*) FROM URBAN_RURAL_DF;

CREATE TABLE URBAN_RURAL (
    FIPS VARCHAR2(5),
    URBAN_RURAL_CODE VARCHAR2(30),
    CONSTRAINT fk_ur_county FOREIGN KEY (FIPS) REFERENCES COUNTIES(FIPS)
);

INSERT INTO URBAN_RURAL (FIPS, URBAN_RURAL_CODE)
SELECT FIPS, URBAN_RURAL_CODE
FROM URBAN_RURAL_DF
WHERE FIPS IN (SELECT FIPS FROM COUNTIES);

DROP TABLE URBAN_RURAL;

SELECT COUNT(*) FROM URBAN_RURAL;

-- 0 Case Count based on Rural/Urban Counties --
SELECT ur.URBAN_RURAL_CODE, COUNT(*) AS zero_case_count
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN CASE_DATA cd ON c.FIPS = cd.FIPS
JOIN URBAN_RURAL ur ON c.FIPS = ur.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
AND (cd.Y2020 + cd.Y2021 + cd.Y2022 + cd.Y2023) = 0
GROUP BY ur.URBAN_RURAL_CODE
ORDER BY ur.URBAN_RURAL_CODE;

-- Case count based on Rural/Urban Counties -- 
SELECT ur.URBAN_RURAL_CODE, COUNT(*) AS total_established_count
FROM COUNTIES c
JOIN TICK_STATUS t ON c.FIPS = t.FIPS
JOIN URBAN_RURAL ur ON c.FIPS = ur.FIPS
WHERE t.SCAPULARIS_STATUS = 'Established'
GROUP BY ur.URBAN_RURAL_CODE
ORDER BY ur.URBAN_RURAL_CODE;

-- Line Graph to Represent Lyme Disease Case Count throughout the years -- 
SELECT INCIDENCE_STATUS,
       SUM(Y2001) AS y2001, SUM(Y2005) AS y2005, SUM(Y2010) AS y2010,
       SUM(Y2015) AS y2015, SUM(Y2019) AS y2019, SUM(Y2020) AS y2020,
       SUM(Y2021) AS y2021, SUM(Y2022) AS y2022, SUM(Y2023) AS y2023
FROM CASE_DATA
GROUP BY INCIDENCE_STATUS;